[package]
edition = "2024"
license = "Apache-2.0"
name    = "blob-stream-sim"
publish = false
version = "0.1.0"

[dependencies]
async-trait.workspace            = true
aws-sdk-s3.workspace             = true
aws-smithy-runtime-api.workspace = true
aws-smithy-types.workspace       = true
bytes.workspace                  = true
futures.workspace                = true
http.workspace                   = true
hyper.workspace                  = true
hyper-util                       = { workspace = true, features = ["tokio"] }
log.workspace                    = true
parking_lot.workspace            = true
s3s.workspace                    = true
tokio.workspace                  = true
turmoil.workspace                = true

[dev-dependencies]
blob-stream-blob-store.path     = "../blob-stream-blob-store"
blob-stream-metadata-store.path = "../blob-stream-metadata-store"
fastrand.workspace              = true
